### ISSUE TITLE
Add css code which is present in html to style.css

### ISSUE THREAD

**Issue by vinayakgavariya** [vinayakgavariya/PlaylistAdda#2]

**Comment by sooraj-gk** [comment]
Can I work on this?

**Comment by VG-1** [comment]
@sooraj-gk yes assigning it to you.
Happy coding

**Comment by DhruvDhari** [comment]
i am first timer... what we exactly need to do? i can help with html and css

**Comment by sooraj-gk** [comment]
Add css code which is present in html to style.css #12

**Comment by sumit-022** [comment]
Can i work on this?
